name: Test Project

on: push

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v5.0.0
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test


  deploy:
    name: Deploy Code
    runs-on:  ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v5.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v5.0.0
        with:
          node-version: 18

      - name: Install dependencies
        run:  npm ci

      - name: Build project
        run: npm run build

      - name: Deploy
        run: echo "deploying"
      